version: 3

services:
  nfs:
    name: nfs
    build:
      context: './'
    image: mohitsharma44/nfsserver-alpine:latest
    ports:
      - "2049:2049"
    volume:
      - /nfsshare:/nfsshare
    environment:
      - SHARED_DIRECTORY=/nfsshare
    privileged: true
